name: car_wrecker
version: 1.0.7+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.5.4
  table_calendar: ^3.0.9
  dio: ^4.0.6
  chewie: ^1.3.6
  video_player: ^2.4.7
  image_picker: 0.8.6
  photo_view: ^0.14.0
  calendar_view: ^1.0.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  path_provider: ^2.0.2
  url_launcher: ^6.0.3
  android_intent: ^2.0.2
  timezone: ^0.9.2
  flutter_phone_direct_caller: ^2.0.1
  flutter_image_compress: ^1.0.0
  flutter:
    sdk: flutter
  flutter_signature_pad: ^3.0.1
  simple_barcode_scanner: ^0.0.8
  scan: ^1.6.0
  flutter_image: ^4.1.9
  flutter_google_places: ^0.3.0
  webview_flutter: ^4.0.0
  # flutter_inappwebview: ^5.3.2
  fl_chart: ^0.40.2
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/pickYourCar.png
    - assets/images/apexpoint.png
    - assets/images/carIcon.jpg
    - assets/images/loadingFailed.jpg
    - assets/images/top_bar_bgk.png
    - assets/images/icon_date.png
    - assets/images/icon_clear.png
    - assets/images/icon_location.png
    - assets/images/icon_refresh.png
    - assets/images/icon_sign.png
    - assets/images/icon_upload.png
    - assets/images/nav_home_nor.png
    - assets/images/nav_home_pre.png
    - assets/images/nav_job_nor.png
    - assets/images/nav_job_pre.png
    - assets/images/nav_my_nor.png
    - assets/images/nav_my_pre.png
    - assets/images/noData.png
  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/BEBAS-1.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
